const mongoose = require("mongoose");

const PostSchema = new mongoose.Schema({
    _id: {
        type: mongoose.Schema.Types.ObjectId,
        auto: true // Automatically generated by MongoDB
    },
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User", // Links the post to a user
        required: true
    },
    content: {
        type: String,
        required: true
    },
    media: {
        type: String // URL or file path of an image/video (optional)
    },
    timestamp: {
        type: Date,
        default: Date.now
    },
    reactions: {
        like: { type: Number, default: 0 },
        love: { type: Number, default: 0 },
        haha: { type: Number, default: 0 },
        wow: { type: Number, default: 0 },
        sad: { type: Number, default: 0 },
        angry: { type: Number, default: 0 },
        favorite: { type: Number, default: 0 }
    }
});

module.exports = mongoose.model("Posts", PostSchema);
